### PR TITLE
Update for SMAPI 1.9, streamline build process, and simplify code

### PR DESCRIPTION
**Pull request by Pathoschild**
Chest Pooling doesn't work in the latest version of SMAPI. Players see this error:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Cecil.MethodSpecification.set_DeclaringType(TypeReference value)
   at StardewModdingAPI.AssemblyRewriters.Rewriters.TypeReferenceRewriter.Rewrite(ModuleDefinition module, ILProcessor cil, Instruction instruction, PlatformAssemblyMap assemblyMap, Boolean platformChanged)
   at StardewModdingAPI.Framework.AssemblyLoader.RewriteAssembly(AssemblyDefinition assembly, Boolean assumeCompatible) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\AssemblyLoader.cs:line 228
   at StardewModdingAPI.Framework.AssemblyLoader.Load(String assemblyPath, Boolean assumeCompatible) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\AssemblyLoader.cs:line 77
   at StardewModdingAPI.Program.LoadMods() in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Program.cs:line 467
```

This pull request mainly...
- Updates the code to the latest SMAPI 1.9 features.
- Formats and simplifies the code a bit (e.g. using SMAPI features where possible).
- Migrates the project to the [mod build package](https://github.com/Pathoschild/Stardew.ModBuildConfig).  
  _This automates references (so we no longer need to change reference paths in the `.csproj`), lets us compile the mod on Linux/Mac/Windows without changes, and simplifies debugging from Visual Studio._
- Switches to a build task to automatically package the mod into the `Mods` folder that works on Linux/Mac/Windows.
- Updates and expands the readme.

If the changes all look good, can you release [ChestPooling-1.3.zip](https://github.com/mralbobo/stardew-chest-pooling/files/938491/ChestPooling-1.3.zip) for players to use?

### CODE REVIEW

**Comment by mralbobo** [comment]
Looks good. Personal beef with single line if short-hand, but eh.

**Comment by mralbobo** [comment]
Moderate curiosity, what specifically in my attempt to migrate blind last month-ish did I miss?
Since the vast majority of the changes look like build tooling/ best practice c# things.

**Comment by Pathoschild** [comment]
A few deprecated things were still around (specifically `Log` and some `manifest.json` fields), but the [error BremkeW reported](http://community.playstarbound.com/threads/smapi-0-40-chest-pooling-gateopener-toolcharging.111988/page-5#post-3147255) seems to happen in rare cases when a mod is compiled with an earlier version of SMAPI but used in SMAPI 1.9. Usually that's fine, but some of the changes in SMAPI 1.9 can lead to incompatibilities.

**Comment by mralbobo** [comment]
Interesting...

**Pull request merged**
